CREATE TABLE payment
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,

    amount NUMERIC(12, 2) NOT NULL,

    status VARCHAR(20) NOT NULL,

    paid_at TIMESTAMP,

    CONSTRAINT uk_payment_order_id
        UNIQUE (order_id),

    CONSTRAINT chk_payment_amount_positive
        CHECK (amount > 0),

    CONSTRAINT chk_payment_status
        CHECK (status IN ('SUCCESS', 'FAILED'))
);