CREATE TABLE authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_authors_name UNIQUE (name)
);

INSERT INTO authors (name)
SELECT DISTINCT author
FROM books;

ALTER TABLE books
    ADD COLUMN author_id BIGINT;

UPDATE books b
SET author_id = a.id
FROM authors a
WHERE a.name = b.author;

ALTER TABLE books
    ALTER COLUMN author_id SET NOT NULL;

ALTER TABLE books
    ADD CONSTRAINT fk_books_author
        FOREIGN KEY (author_id)
            REFERENCES authors (id);

ALTER TABLE books
    DROP COLUMN author;
