spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    driver-class-name: org.postgresql.Driver
    username: bookstore_user
    password: bookstore_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  port: 8080