CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_orders_status
        CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'SHIPPED')),

    CONSTRAINT chk_orders_total_price_non_negative
        CHECK (total_price >= 0)
);


CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_order_item_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_order_item_unit_price_positive
        CHECK (unit_price > 0)
);


CREATE INDEX idx_orders_user_id
    ON orders (user_id);

CREATE INDEX idx_order_item_order_id
    ON order_item (order_id);