server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            - id: book-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/books/**

            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders/**

            - id: payment-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/payments/**

jwt:
  secret: ${JWT_SECRET:Ym9va3N0b3JlLWRldi1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcyE=}
