spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_service_db
    driver-class-name: org.postgresql.Driver
    username: bookstore_user
    password: bookstore_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET:Ym9va3N0b3JlLWRldi1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcyE=}
